/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.povmodeler.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "povmodeleradaptator.h"
#include "povmodeleradaptator.moc"

povmodelerAdaptor::povmodelerAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

povmodelerAdaptor::~povmodelerAdaptor()
{
    // destructor
}

QString povmodelerAdaptor::activeObjectName()
{
    // handle method call org.povmodeler.activeObjectName
    QString out0;
    QMetaObject::invokeMethod(parent(), "activeObjectName", Q_RETURN_ARG(QString, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->activeObjectName();
    return out0;
}

void povmodelerAdaptor::clearSelection()
{
    // handle method call org.povmodeler.clearSelection
    QMetaObject::invokeMethod(parent(), "clearSelection");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->clearSelection();
}

void povmodelerAdaptor::closeDocument()
{
    // handle method call org.povmodeler.closeDocument
    QMetaObject::invokeMethod(parent(), "closeDocument");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->closeDocument();
}

void povmodelerAdaptor::deleteContents()
{
    // handle method call org.povmodeler.deleteContents
    QMetaObject::invokeMethod(parent(), "deleteContents");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->deleteContents();
}

QStringList povmodelerAdaptor::getObjectTypes()
{
    // handle method call org.povmodeler.getObjectTypes
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getObjectTypes", Q_RETURN_ARG(QStringList, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->getObjectTypes();
    return out0;
}

QStringList povmodelerAdaptor::getProperties()
{
    // handle method call org.povmodeler.getProperties
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "getProperties", Q_RETURN_ARG(QStringList, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->getProperties();
    return out0;
}

void povmodelerAdaptor::initDocument()
{
    // handle method call org.povmodeler.initDocument
    QMetaObject::invokeMethod(parent(), "initDocument");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->initDocument();
}

void povmodelerAdaptor::newDocument()
{
    // handle method call org.povmodeler.newDocument
    QMetaObject::invokeMethod(parent(), "newDocument");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->newDocument();
}

bool povmodelerAdaptor::setActiveObject(const QString &name)
{
    // handle method call org.povmodeler.setActiveObject
    bool out0;
    QMetaObject::invokeMethod(parent(), "setActiveObject", Q_RETURN_ARG(bool, out0), Q_ARG(QString, name));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->setActiveObject(name);
    return out0;
}

bool povmodelerAdaptor::setProperty(const QString &property, const QString &value)
{
    // handle method call org.povmodeler.setProperty
    bool out0;
    QMetaObject::invokeMethod(parent(), "setProperty", Q_RETURN_ARG(bool, out0), Q_ARG(QString, property), Q_ARG(QString, value));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->setProperty(property, value);
    return out0;
}

void povmodelerAdaptor::slotEditCopy()
{
    // handle method call org.povmodeler.slotEditCopy
    QMetaObject::invokeMethod(parent(), "slotEditCopy");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotEditCopy();
}

void povmodelerAdaptor::slotEditCut()
{
    // handle method call org.povmodeler.slotEditCut
    QMetaObject::invokeMethod(parent(), "slotEditCut");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotEditCut();
}

void povmodelerAdaptor::slotEditDelete()
{
    // handle method call org.povmodeler.slotEditDelete
    QMetaObject::invokeMethod(parent(), "slotEditDelete");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotEditDelete();
}

void povmodelerAdaptor::slotEditPaste()
{
    // handle method call org.povmodeler.slotEditPaste
    QMetaObject::invokeMethod(parent(), "slotEditPaste");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotEditPaste();
}

void povmodelerAdaptor::slotNewObject(const QString &type, const QString &pos)
{
    // handle method call org.povmodeler.slotNewObject
    QMetaObject::invokeMethod(parent(), "slotNewObject", Q_ARG(QString, type), Q_ARG(QString, pos));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotNewObject(type, pos);
}

void povmodelerAdaptor::slotRender()
{
    // handle method call org.povmodeler.slotRender
    QMetaObject::invokeMethod(parent(), "slotRender");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotRender();
}

